# Generated by Django 5.0.1 on 2024-01-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userpreferences", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userpreference", old_name="currentcy", new_name="currency",
        ),
    ]
